name: Docker

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the PR's image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: true
          tags: ghcr.io/gear-foundation/gear-env:pr-${{ github.event.number }}

      - name: Build and push the latest image (master)
        if: github.event_name == 'push' && endsWith(github.ref, 'master')
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: true
          tags: ghcr.io/gear-foundation/gear-env:latest

      - name: Get version from tag
        if: github.event_name == 'push' && !endsWith(github.ref, 'master')
        id: version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Show version
        if: github.event_name == 'push' && !endsWith(github.ref, 'master')
        run: echo ${{ steps.version.outputs.VERSION }}

      - name: Build and push the stable image (tag)
        if: github.event_name == 'push' && !endsWith(github.ref, 'master')
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: true
          tags: >-
            ghcr.io/gear-foundation/gear-env:${{ steps.version.outputs.VERSION }},
            ghcr.io/gear-foundation/gear-env:stable

  test:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: ghcr.io/gear-foundation/gear-env:pr-${{ github.event.number }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: gear-foundation/dapp-template

      - name: List versions
        run: |
          rustc +stable --version
          rustc +nightly --version
          node --version
          yarn --version
          gear --version

      - name: Run `dapp-template` tests
        run: cargo xtask ci
